{"kind":"issue","data":{"line":6,"column":11,"path":"test.py","code":5001,"name":"User controlled data may lead to remote code execution.","description":"User controlled data may lead to remote code execution. [5001]: Flow from @test.py:5:24-5:26 -> {UserControlled} to @test.py:6:11-6:12 -> {RemoteCodeExecution} detected.","inference":null,"define":"rce_problem"}}
